---
# this simple tasksm get´s running vm´s of an azurestack subscription
platform: linux

inputs:
 - name: dps_modules

params:
  GOVC_INSECURE: 
  GOVC_PASSWORD: 
  GOVC_URL: 
  GOVC_USERNAME: 
  PPDM_VMNAME:

  

run:
  path: dps_modules/ci/scripts/add-ppdm-vproxy.sh


# test with 
# echo "<preset variable yml>" > vars.yml
# while IFS=": " read -r field1 field2; do     export $field1=$field2; done < vars.yml