---
# this simple tasksm get´s running vm´s of an azurestack subscription
platform: linux

inputs:
 - name: dps-modules
 - name: dps-ansible
 - name: ppdm-config
   optional: true
 - name: vars
   optional: true  
params:
  PLAYBOOK:
  

run:
  path: dps-modules/ci/scripts/ansible-playbook.sh


# test with 
# echo "<preset variable yml>" > vars.yml
# while IFS=": " read -r field1 field2; do     export $field1=$field2; done < vars.yml