---
# this simple tasksm get´s running vm´s of an azurestack subscription
platform: linux

inputs:
 - name: dps-modules


params:
  PPDD_FQDN: 
  PPDD_USERNAME:
  PPDD_PASSWORD:
  PPDD_SETUP_PASSWORD:

run:
  path: dps-modules/ci/scripts/change-ppdd-password.sh

# test with 
# echo "<preset variable yml>" > vars.yml
# while IFS=": " read -r field1 field2; do     export $field1=$field2; done < vars.yml