---
# this simple tasksm get´s running vm´s of an azurestack subscription
platform: linux

inputs:
 - name: dps-modules


params:
  PPDM_NTP_SERVER: "192.168.1.1"
  PPDM_NETWORK: 
  PPDM_ADDRESS: 
  PPDM_GATEWAY: 
  PPDM_NETMASK: 
  PPDM_FQDN: 
  PPDM_VMNAME:
  PPDM_DNS:
  PPDM_PASSWORD: "Password123!"
  PPDM_SETUP_PASSWORD: "admin"
  

run:
  path: dps-modules/ci/scripts/configure-ppdm.sh


# test with 
# echo "<preset variable yml>" > vars.yml
# while IFS=": " read -r field1 field2; do     export $field1=$field2; done < vars.yml