---
# this simple tasksm get´s running vm´s of an azurestack subscription
platform: linux

inputs:
 - name: dps-modules
 - name: ppdm-config
   optional: true
params:
  PPDM_NTP_SERVER:
  PPDM_FQDN: 
  PPDM_PASSWORD: 
  PPDM_SETUP_PASSWORD: "admin"
  

run:
  path: dps-modules/ci/scripts/configure-ppdm.sh


# test with 
# echo "<preset variable yml>" > vars.yml
# while IFS=": " read -r field1 field2; do     export $field1=$field2; done < vars.yml