---
# this simple tasksm get´s running vm´s of an azurestack subscription
platform: linux

inputs:
 - name: dps_modules


params:

  DDVE_NETWORK: 
  DDVE_ADDRESS: 
  DDVE_GATEWAY: 
  DDVE_NETMASK: 
  DDVE_FQDN: 
  DDVE_VMNAME:
  DDVE_DNS:
  DDVE_FOLDER:
  DDVE_INTERFACE:
  DDVE_TYPE:
  DDVE_USERNAME:
  DDVE_PASSWORD:
  DDVE_NFS_PATH:

run:
  path: dps_modules/ci/scripts/configure-ppdd.sh


# test with 
# echo "<preset variable yml>" > vars.yml
# while IFS=": " read -r field1 field2; do     export $field1=$field2; done < vars.yml