---
# this simple tasksm get´s running vm´s of an azurestack subscription
platform: linux

inputs:
 - name: dps-modules
 - name: kubeconfig
 - name: aksconfig
 - name: dps-ansible
 - name: ppdm-config
   optional: true 
outputs: 
 - name: k8stoken
params:
  DEBUG: "FALSE"
  PPDM_K8S_FILE: ppdmk8stoken-$timestamp.json
  PPDM_RBAC_TEMPLATE: dps-modules/ci/templates/ppdm/ppdm-rbac.yml
  PPDM_ADMIN_TEMPLATE: dps-modules/ci/templates/ppdm/ppdm-admin.yml
  PLAYBOOK:
  AKS_CLUSTER_NAME:
 

run:
  path: dps-modules/ci/scripts/configure-k8s-ppdm.sh

