---
# this simple tasksm get´s running vm´s of an azurestack subscription
platform: linux

inputs:
 - name: dps-modules


params:

  PPDD_NETWORK: 
  PPDD_ADDRESS: 
  PPDD_GATEWAY: 
  PPDD_NETMASK: 
  PPDD_FQDN: 
  PPDD_VMNAME:
  PPDD_DNS:
  PPDD_FOLDER:
  PPDD_INTERFACE:
  PPDD_TYPE:
  PPDD_USERNAME:
  PPDD_PASSWORD:
  PPDD_SETUP_PASSWORD:
  PPDD_NFS_PATH:

run:
  path: dps-modules/ci/scripts/configure-ppdd.sh


# test with 
# echo "<preset variable yml>" > vars.yml
# while IFS=": " read -r field1 field2; do     export $field1=$field2; done < vars.yml