---
# this simple tasksm get´s running vm´s of an azurestack subscription
platform: linux

inputs:
 - name: dps_modules


params:
  DEBUG: false
  GOVC_INSECURE: 
  GOVC_PASSWORD: 
  GOVC_URL: 
  GOVC_USERNAME:
  GOVC_RESOURCE_POOL: 
  GOVC_DATASTORE: 
  GOVC_DATACENTER:   
  GOVC_NETWORK: 
  GOVC_VM_IPATH:
  AVE_FQDN:
  AVE_USERNAME:
  AVE_PASSWORD:
  AVE_UPGRADE_CLIENT_DOWNLOADS_PACKAGE:
  AVE_UPGRADE_CLIENT_DOWNLOADS_URL:

  

run:
  path: dps_modules/ci/scripts/deploy-avamar-client-avp-rest.sh


# test with 
# echo "<preset variable yml>" > vars.yml
# while IFS=": " read -r field1 field2; do     export $field1=$field2; done < vars.yml