---
# this simple tasksm get´s running vm´s of an azurestack subscription
platform: linux

inputs:
 - name: dps-modules
 - name: ddve
outputs:


params:
  GOVC_INSECURE: 
  GOVC_PASSWORD: 
  GOVC_URL: 
  GOVC_USERNAME: Administrator@vsphere.local
  GOVC_RESOURCE_POOL: 
  GOVC_DATASTORE: 
  GOVC_DATACENTER:   
  GOVC_NETWORK: 
  PPDD_NETWORK: 
  PPDD_ADDRESS: 
  PPDD_GATEWAY: 
  PPDD_NETMASK: 
  PPDD_FQDN: 
  PPDD_VMNAME:
  PPDD_DNS:
  PPDD_FOLDER:
  PPDD_INTERFACE:
  PPDD_TYPE:

run:
  path: dps-modules/ci/scripts/deploy-ppdd.sh


# test with 
# echo "<preset variable yml>" > vars.yml
# while IFS=": " read -r field1 field2; do     export $field1=$field2; done < vars.yml