---
# this simple tasksm get´s running vm´s of an azurestack subscription
platform: linux

inputs:
 - name: dps_modules
 - name: avamar


params:
  DEBUG: false
  GOVC_INSECURE: 
  GOVC_PASSWORD: 
  GOVC_URL: 
  GOVC_USERNAME: Administrator@vsphere.local
  GOVC_RESOURCE_POOL: 
  GOVC_DATASTORE: 
  GOVC_DATACENTER:   
  GOVC_NETWORK: 
  GOVC_VM_IPATH:
  AVE_FOLDER:
  AVE_NETWORK: 
  AVE_ADDRESS: 
  AVE_GATEWAY: 
  AVE_NETMASK: 
  AVE_FQDN: 
  AVE_VMNAME:
  AVE_DNS:
  AVE_SIZE: 0.5TB 
  

run:
  path: dps_modules/ci/scripts/deploy-ave.sh


# test with 
# echo "<preset variable yml>" > vars.yml
# while IFS=": " read -r field1 field2; do     export $field1=$field2; done < vars.yml