---
# this simple tasksm get´s running vm´s of an azurestack subscription
platform: linux

inputs:
 - name: dps-modules
 - name: kubeconfig
   optional: true 

params:
  DEBUG: "FALSE"
  PPDM_K8S_FILE: ppdmk8stoken-$timestamp.json
  NAMESPACE: mysql
  MYSQL_NAMESPACE: dps-modules/ci/templates/mysql/mysql-namespace.yaml
  MYSQL_SECRET: dps-modules/ci/templates/mysql/mysql-secret.yaml
  MYSQL_PVC: dps-modules/ci/templates/mysql/mysql-pvc.yaml
  MYSQL_DEPLOYMENT: dps-modules/ci/templates/mysql/mysql-deployment.yaml
  PLAYBOOK:
  AKS_CLUSTER_NAME:
 

run:
  path: dps-modules/ci/scripts/deploy-mysql-k8s.sh
