---
# this simple tasksm get´s running vm´s of an azurestack subscription
platform: linux

inputs:
 - name: dps_modules
 - name: ddve
outputs:


params:
  GOVC_INSECURE: 
  GOVC_PASSWORD: 
  GOVC_URL: 
  GOVC_USERNAME: Administrator@vsphere.local
  GOVC_RESOURCE_POOL: 
  GOVC_DATASTORE: 
  GOVC_DATACENTER:   
  GOVC_NETWORK: 
  DDVE_NETWORK: 
  DDVE_ADDRESS: 
  DDVE_GATEWAY: 
  DDVE_NETMASK: 
  DDVE_FQDN: 
  DDVE_VMNAME:
  DDVE_DNS:
  DDVE_FOLDER:
  DDVE_INTERFACE:
  DDVE_TYPE:

run:
  path: dps_modules/ci/scripts/deploy-ppdd.sh


# test with 
# echo "<preset variable yml>" > vars.yml
# while IFS=": " read -r field1 field2; do     export $field1=$field2; done < vars.yml