---
platform: linux

inputs:
 - name: dps-modules

params:
  avamar: 
  packages:
  extension: ova
  AV_LOCATION:
  AV_RELEASE:
  DEBUG: false
outputs:
  - name: AvamarUpgrade
  - name: UpgradeAvinstaller
  - name: UpgradeClientDownloads
  - name: UpgradeClientPluginCatalog 
  - name: ChangeNetworkSettings
  - name: AVE
  - name: AZURE-AVE
run:
  path: dps-modules/ci/scripts/download-avamar-packages.sh