---
platform: linux

inputs:
 - name: dps_modules

params:
  avamar: 
  packages:
  extension: ova
  AV_LOCATION:
  AV_RELEASE:
outputs:
  - name: AvamarUpgrade
  - name: UpgradeAvinstaller
  - name: UpgradeClientDownloads
  - name: UpgradeClientPluginCatalog 
  - name: ChangeNetworkSettings
  - name: AVE
  - name: AZURE-AVE
run:
  path: dps_modules/ci/scripts/download-avamar-packages.sh