---
# this simple tasksm get´s running vm´s of an azurestack subscription
platform: linux

inputs:
 - name: dps-modules
 - name: variable
outputs:
 - name: instant_access
params:
  INSTANT_FILE: $vmName-$timestamp.json
  GOVC_INSECURE: 
  GOVC_PASSWORD: 
  GOVC_URL: 
  GOVC_USERNAME: 
  PROXY_FILE:

run:
  path: dps-modules/ci/scripts/ppdm-vm-instant-access.sh


# test with 
# echo "<preset variable yml>" > vars.yml
# while IFS=": " read -r field1 field2; do     export $field1=$field2; done < vars.yml