---
# this simple tasksm get´s running vm´s of an azurestack subscription
platform: linux

inputs:
 - name: dps_modules
 - name: variable

params:
  GOVC_INSECURE: 
  GOVC_PASSWORD: 
  GOVC_URL: 
  GOVC_USERNAME: 
  PROXY_FILE:

run:
  path: dps_modules/ci/scripts/ppdm-vm-instant-access.sh


# test with 
# echo "<preset variable yml>" > vars.yml
# while IFS=": " read -r field1 field2; do     export $field1=$field2; done < vars.yml