---
# this simple tasksm get´s running vm´s of an azurestack subscription
platform: linux

inputs:
 - name: dps-modules
 - name: cdra-active
outputs:
 - name: cdra-active
params:
  CDRA_STATE_FILE: cdra-state-$timestamp.json
  PPDM_FQDN:
  PPDM_PASSWORD:
  PPDM_USERNAME: admin
  PPDM_QUERY: CLOUD_PROTECT
  PPDM_FILTER: RUNNING

run:
  path: dps-modules/ci/scripts/query-ppdm-activities.sh

