---
# this simple tasksm get´s running vm´s of an azurestack subscription
platform: linux

inputs:
 - name: dps-modules
# - name: variable
outputs:
 - name: cdrs-state
params:
  CDRS_STATE_FILE: cdrs-state-$timestamp.json
  PPDM_FQDN:
  PPDM_PASSWORD:
  PPDM_USERNAME: admin
run:
  path: dps-modules/ci/scripts/query-cdrs-state.sh

