---
# this simple tasksm get´s running vm´s of an azurestack subscription
platform: linux

inputs:
 - name: dps-modules
 - name: ppdm-config
   optional: true
params:
  PPDM_FQDN: 
  PPDM_PASSWORD: 
  PPDD_PATH:
  PPDD_FQDN:
run:
  path: dps-modules/ci/scripts/set-ppdm-sdr.sh


# test with 
# echo "<preset variable yml>" > vars.yml
# while IFS=": " read -r field1 field2; do     export $field1=$field2; done < vars.yml