---
# this simple tasksm get´s running vm´s of an azurestack subscription
platform: linux

inputs:
 - name: dps-modules
 - name: ppdm-config
   optional: true
params:
  PPDM_FQDN: 
  PPDM_PASSWORD: 
  INVENTORY_USERNAME: 
  INVENTORY_PASSWORD: 
  INVENTORY_FQDN:
  INVENTORY_TYPE:
  INVENTORY_CREDENTIAL_TYPE:
  INVENTORY_PORT:
run:
  path: dps-modules/ci/scripts/set-ppdm-inventory.sh


# test with 
# echo "<preset variable yml>" > vars.yml
# while IFS=": " read -r field1 field2; do     export $field1=$field2; done < vars.yml