---
# this simple tasksm get´s running vm´s of an azurestack subscription
platform: linux

inputs:
 - name: dps-modules
# - name: variable
#outputs:
# - name: cdrs-state
params:
  CDRS_INSTANCE_NAME: CDRS-Instance 
  CDRS_RESOURCE_GROUP: CDRS-ResourceGroup
run:
  path: dps-modules/ci/scripts/stop-cdrs-services.sh

