
---
platform: linux
inputs:
- name: dps-modules
outputs:
- name: terraform-output
caches:
- path: .tfcache
params:
  TFSTATE: tf-output-$timestamp.json
  TF_OUTPUT_DIR: terraform-output
  TF_PLUGIN_CACHE: .tfcache
  STATE_FILE_PATH:
  DEBUG:
run:
  path: dps-modules/ci/scripts/terraform-output.sh
