kind: Namespace
apiVersion: v1
metadata:
  name: powerprotect
  labels:
    app.kubernetes.io/part-of: powerprotect.dell.com
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: ppdm-serviceaccount
  namespace: powerprotect
  labels:
    app.kubernetes.io/part-of: powerprotect.dell.com
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: powerprotect:cluster-role
  labels:
    app.kubernetes.io/part-of: powerprotect.dell.com
rules:
  - apiGroups: [ "rbac.authorization.k8s.io" ]
    resources: [ "clusterrolebindings" ]
    verbs: [ "create", "get", "list" ]
  - apiGroups: [ "rbac.authorization.k8s.io" ]
    resources: [ "clusterroles" ]
    verbs: [ "bind" ]
    resourceNames: [ "cluster-admin" ]
  - apiGroups: [ "" ]
    resources: [ "namespaces" ]
    verbs: [ "create", "delete", "get", "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "create","get","delete" ]
  - apiGroups: [ "" ]
    resources: [ "events" ]
    verbs: [ "get", "list" ]
  - apiGroups: [ "" ]
    resources: [ "serviceaccounts" ]
    verbs: [ "create", "get" ]
  - apiGroups: [ "" ]
    resources: [ "persistentvolumeclaims" ]
    verbs: [ "create", "get", "list", "update", "watch", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "persistentvolumes" ]
    verbs: [ "get", "delete", "list", "update" ]
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "create", "get", "list", "update", "watch", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "pods/exec" ]
    verbs: [ "create" ]
  - apiGroups: [ "" ]
    resources: [ "pods/log" ]
    verbs: [ "get" ]
  - apiGroups: [ "" ]
    resources: [ "replicationcontrollers", "replicationcontrollers/scale" ]
    verbs: [ "update", "watch" ]
  - apiGroups: [ "apps" ]
    resources: [ "deployments", "deployments/scale" ]
    verbs: [ "create", "get", "list", "patch", "update", "watch", "delete" ]
  - apiGroups: [ "apps" ]
    resources: [ "replicasets", "replicasets/scale" ]
    verbs: [ "get", "list", "update", "watch" ]
  - apiGroups: [ "apps" ]
    resources: [ "daemonsets", "daemonset/scale" ]
    verbs: [ "get", "list", "update", "watch" ]
  - apiGroups: [ "apps" ]
    resources: [ "statefulsets", "statefulsets/scale" ]
    verbs: [ "get", "list", "update", "watch" ]
  - apiGroups: [ "storage.k8s.io" ]
    resources: [ "storageclasses" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "apiextensions.k8s.io" ]
    resources: [ "customresourcedefinitions" ]
    verbs: [ "create", "get", "update", "list", "delete" ]
  - apiGroups: [ "snapshot.storage.k8s.io" ]
    resources: [ "volumesnapshotclasses" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "snapshot.storage.k8s.io" ]
    resources: [ "volumesnapshots" ]
    verbs: [ "create", "get", "list", "watch", "delete" ]
  - apiGroups: [ "snapshot.storage.k8s.io" ]
    resources: [ "volumesnapshotcontents" ]
    verbs: [ "create", "get", "list", "watch", "delete" ]
  - apiGroups: [ "powerprotect.dell.com", "velero.io" ]
    resources: [ '*' ]
    verbs: [ '*' ]
  - apiGroups: [ "" ]
    resources: [ "services" ]
    verbs: [ "create", "get", "list", "update", "watch", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "create", "get", "list", "update", "watch", "delete" ]
  - apiGroups: [ "backupdriver.cnsdp.vmware.com" ]
    resources: [ "snapshots" ]
    verbs: [ "create", "get", "list", "update", "watch", "delete" ]
  - apiGroups: [ "backupdriver.cnsdp.vmware.com" ]
    resources: [ "deletesnapshots" ]
    verbs: [ "create", "get", "list", "update", "watch", "delete" ]
  - apiGroups: [ "backupdriver.cnsdp.vmware.com" ]
    resources: [ "deletesnapshots/status" ]
    verbs: [ "create", "get", "list", "update", "watch", "delete" ]
  - apiGroups: ["networking.k8s.io"]
    resources: [ "networkpolicies" ]
    verbs: ["create", "delete", "get"]
  - apiGroups: ["operators.coreos.com"]
    resources: [ '*' ]
    verbs: [ '*' ]
  - apiGroups: [ "konveyor.openshift.io" ]
    resources: [ '*' ]
    verbs: [ '*' ]
  - apiGroups: [ "oadp.openshift.io" ]
    resources: [ '*' ]
    verbs: [ '*' ]
  - apiGroups: [ "volumegroup.storage.dell.com" ]
    resources: [ "dellcsivolumegroupsnapshots" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete", "deletecollection" ]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: powerprotect:cluster-role-binding
  labels:
    app.kubernetes.io/part-of: powerprotect.dell.com
subjects:
  - kind: ServiceAccount
    name: ppdm-serviceaccount
    namespace: powerprotect
roleRef:
  kind: ClusterRole
  name: powerprotect:cluster-role
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ppdmrole
  namespace: powerprotect
  labels:
    app.kubernetes.io/part-of: powerprotect.dell.com
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ppdmrolebinding
  namespace: powerprotect
  labels:
    app.kubernetes.io/part-of: powerprotect.dell.com
roleRef:
  kind: Role
  name: ppdmrole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: ppdm-serviceaccount
    namespace: powerprotect
